### ISSUE TITLE
ambiguous output for Import-index-templates.sh

### ISSUE THREAD

**Issue by neu5ron** [rocknsm/rock-dashboards#15]
https://community.rocknsm.io/t/import-index-templates-sh-fails-2-2-0-fresh-install/128
The output for Import-index-templates.sh is a bi t ambiguous.

Despite the output error I still believe the import is successful, per documentation it may be helpful to add a note to ignore this error if that is the case.
Error/output looks as follows:
```
root@simplerockbuild elasticsearch]# pwd
/opt/rocknsm/rock-dashboards-master/configuration/elasticsearch

[root@simplerockbuild elasticsearch]# ./import-index-templates.sh http://127.0.0.1:9200
jq: error: syntax error, unexpected IDENT, expecting $end (Unix shell quoting issues?) at <top-level>, line 2:
mappings
jq: 1 compile error
./import-index-templates.sh: line 31: [: : integer expression expected
OK: 4
Changed: 0
Failed: 0
```

**Comment by dcode** [comment]
the import/export scripts aren't working as expected. Need to figure this out and fix them. Namely, the imports need to import the object by their ID, ensuring that the action is idempotent

**Comment by dcode** [comment]
Check the output of the curl commands used during import/ export
