### ISSUE TITLE
Dashboards load but are missing data

### ISSUE THREAD

**Issue by dcode** [rocknsm/rock-dashboards#26]
Hopefully this is the last "legacy" dashboard release, but we gotta make it count. The dashboards load, but there are missing references and about 75% of the potential bro fields, and maybe half the suricata fields in the Kibana index pattern.

@spartan782 and I will work on this together with his standard demo dashboards as a start.

**Comment by collse** [comment]
has this been addressed? see still a lot of broken dashboards as visualisations, searches etc arent imported on 2.4.2
