### ISSUE TITLE
Fix hard coded IP in index patterns

### ISSUE THREAD

**Issue by webhead404** [rocknsm/rock-dashboards#62]
The hardcoded IP address addressed here in commit: 2c73726 still applies to ecs index patterns

https://github.com/rocknsm/rock-dashboards/blob/master/ecs-configuration/kibana/index-pattern/ecs-all.ndjson

**Comment by peasead** [comment]
Verified, this is an artifact of the export script from the VM that it was collected from.

@bndabbs @dcode do you know what this _should_ be or how to sanitize it?

**Comment by peasead** [comment]
![image](https://user-images.githubusercontent.com/7442091/82923050-03e0aa00-9f40-11ea-9405-c7e70f8603aa.png)

@bndabbs @dcode any thoughts on how to sanitize this? Likely an artifact of the export script for dashboards. This prevents Docket from working.

**Comment by dcode** [comment]
In the calculated field in the index pattern (each of the index patterns), make the URL relative to the host... i.e. `/app/docket/uri/blah` or whatever. Delete all the `http://1.2.3.4`.

**Comment by peasead** [comment]
```
{"attributes":{"fieldFormatMap":"{\"event.duration\":{\"id\":\"duration\",\"params\":{\"parsedUrl\":
{\"origin\":\"https://172.16.181.137\",\"pathname\":\"/app/kibana\",\"basePath\":\"\"},\"inputFormat\":
\"nanoseconds\"}},\"conn.duration\":{\"id\":\"duration\",\"params\":{\"parsedUrl\":
{\"origin\":\"https://172.16.181.137\",\"pathname\":\"/app/kibana\",\"basePath\":\"\"},\"inputFormat\":
\"nanoseconds\"}},\"files.duration\":{\"id\":\"duration\",\"params\":{\"parsedUrl\":
{\"origin\":\"https://172.16.181.137\",\"pathname\":\"/app/kibana\",\"basePath\":\"\"}}},\"pcap.query\"
:{\"id\":\"url\",\"params\":{\"parsedUrl\":
...
```
That won't fix the build. The index pattern needs to be fixed in the repo so that when ROCK is built, it uses the URL relative to the host.

**Comment by peasead** [comment]
@bndabbs and I are working on this.

**Comment by peasead** [comment]
Needs to be done in `ecs-all...` and `ecs-suricata...`

**Comment by peasead** [comment]
pushed a fix into `master`. doing tests.

**Comment by peasead** [comment]
Appears to be fix't in this release: https://mirror.rocknsm.io/isos/testing/rocknsm-20200607-18:58:06.iso

Recommended pushing into Stable.

**Comment by peasead** [comment]
As a workaround, you can do this:
1. download [ecs-all.ndjson](https://raw.githubusercontent.com/rocknsm/rock-dashboards/master/ecs-configuration/kibana/index-pattern/ecs-all.ndjson) and [ecs-suricata.ndjson](https://raw.githubusercontent.com/rocknsm/rock-dashboards/master/ecs-configuration/kibana/index-pattern/ecs-suricata-all.ndjson). You can do this manually or from the sensor using `curl`
```
curl -OL https://raw.githubusercontent.com/rocknsm/rock-dashboards/master/ecs-configuration/kibana/index-pattern/ecs-suricata-all.ndjson
curl -OL https://raw.githubusercontent.com/rocknsm/rock-dashboards/master/ecs-configuration/kibana/index-pattern/ecs-all.ndjson
```
2. Copy these index patterns so they can be deployed
```
sudo cp ecs-suricata-all.ndjson ecs-all.ndjson /opt/rocknsm/rock-dashboards-master/ecs-configuration/kibana/index-pattern/
sudo chmod 664 /opt/rocknsm/rock-dashboards-master/ecs-configuration/kibana/index-pattern/ecs-suricata-all.ndjson
sudo chmod 664 /opt/rocknsm/rock-dashboards-master/ecs-configuration/kibana/index-pattern/ecs-all.ndjson
```
3. Run the import script to reload the corrected Index Patterns
```
cd /opt/rocknsm/rock-dashboards-master/ecs-configuration/kibana/
sudo sh import-saved-items.sh
```
_Should_ work. LMK

We're building this into the ISO, final testing happening.
